services:
  database:
    container_name: database
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: microservices
      MYSQL_ROOT_PASSWORD: Passw0rd.
    image: mysql
    healthcheck:
        test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
        timeout: 10s
        retries: 10
        interval: 10s
        start_period: 10s
    networks:
      - msnw

  configserver:
    image: abhilasha1307/configserver:s6
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - msnw

  accounts:
    image: abhilasha1307/accounts:s6
    container_name: accounts-ms
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_healthy
    networks:
      - msnw
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_URL: "jdbc:mysql://database:3306/microservices"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Passw0rd.

  cards:
    image: abhilasha1307/cards:s6
    container_name: cards-ms
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_healthy
    networks:
      - msnw
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_URL: "jdbc:mysql://database:3306/microservices"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Passw0rd.

  loans:
    image: abhilasha1307/loans:s6
    container_name: loans-ms
    ports:
      - "8083:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_healthy
    networks:
      - msnw
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_URL: "jdbc:mysql://database:3306/microservices"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Passw0rd.

networks:
  msnw:
    driver: "bridge"